# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := cc_cc_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,STATIC_LIBRARIES,skia_skia_gyp)/skia_skia_gyp.a \
	$(call intermediates-dir-for,STATIC_LIBRARIES,ui_gl_gl_gyp)/ui_gl_gl_gyp.a

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_CPP_EXTENSION := .cc
LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	cc/active_animation.cc \
	cc/animation_curve.cc \
	cc/bitmap_content_layer_updater.cc \
	cc/bitmap_skpicture_content_layer_updater.cc \
	cc/caching_bitmap_content_layer_updater.cc \
	cc/checkerboard_draw_quad.cc \
	cc/content_layer.cc \
	cc/content_layer_updater.cc \
	cc/contents_scaling_layer.cc \
	cc/damage_tracker.cc \
	cc/debug_border_draw_quad.cc \
	cc/debug_rect_history.cc \
	cc/delay_based_time_source.cc \
	cc/delegated_renderer_layer.cc \
	cc/delegated_renderer_layer_impl.cc \
	cc/direct_renderer.cc \
	cc/draw_quad.cc \
	cc/font_atlas.cc \
	cc/frame_rate_controller.cc \
	cc/frame_rate_counter.cc \
	cc/geometry_binding.cc \
	cc/gl_renderer.cc \
	cc/heads_up_display_layer.cc \
	cc/heads_up_display_layer_impl.cc \
	cc/image_layer_updater.cc \
	cc/image_layer.cc \
	cc/io_surface_draw_quad.cc \
	cc/io_surface_layer.cc \
	cc/io_surface_layer_impl.cc \
	cc/keyframed_animation_curve.cc \
	cc/layer.cc \
	cc/layer_animation_controller.cc \
	cc/layer_impl.cc \
	cc/layer_iterator.cc \
	cc/layer_quad.cc \
	cc/layer_sorter.cc \
	cc/layer_tiling_data.cc \
	cc/layer_tree_host.cc \
	cc/layer_tree_host_common.cc \
	cc/layer_tree_host_impl.cc \
	cc/layer_updater.cc \
	cc/managed_memory_policy.cc \
	cc/math_util.cc \
	cc/nine_patch_layer.cc \
	cc/nine_patch_layer_impl.cc \
	cc/occlusion_tracker.cc \
	cc/overdraw_metrics.cc \
	cc/page_scale_animation.cc \
	cc/picture.cc \
	cc/picture_layer.cc \
	cc/picture_layer_impl.cc \
	cc/picture_pile.cc \
	cc/prioritized_resource.cc \
	cc/prioritized_resource_manager.cc \
	cc/priority_calculator.cc \
	cc/program_binding.cc \
	cc/proxy.cc \
	cc/quad_culler.cc \
	cc/rate_limiter.cc \
	cc/region.cc \
	cc/render_pass.cc \
	cc/render_pass_draw_quad.cc \
	cc/render_surface.cc \
	cc/render_surface_filters.cc \
	cc/render_surface_impl.cc \
	cc/renderer.cc \
	cc/rendering_stats.cc \
	cc/resource.cc \
	cc/resource_provider.cc \
	cc/resource_update.cc \
	cc/resource_update_controller.cc \
	cc/resource_update_queue.cc \
	cc/scheduler.cc \
	cc/scheduler_state_machine.cc \
	cc/scoped_resource.cc \
	cc/scoped_thread_proxy.cc \
	cc/scrollbar_animation_controller.cc \
	cc/scrollbar_animation_controller_linear_fade.cc \
	cc/scrollbar_geometry_fixed_thumb.cc \
	cc/scrollbar_geometry_stub.cc \
	cc/scrollbar_layer.cc \
	cc/scrollbar_layer_impl.cc \
	cc/settings.cc \
	cc/shader.cc \
	cc/shared_quad_state.cc \
	cc/single_thread_proxy.cc \
	cc/skpicture_content_layer_updater.cc \
	cc/software_renderer.cc \
	cc/solid_color_draw_quad.cc \
	cc/solid_color_layer.cc \
	cc/solid_color_layer_impl.cc \
	cc/stream_video_draw_quad.cc \
	cc/switches.cc \
	cc/texture_copier.cc \
	cc/texture_draw_quad.cc \
	cc/texture_layer.cc \
	cc/texture_layer_impl.cc \
	cc/texture_uploader.cc \
	cc/thread_impl.cc \
	cc/thread_proxy.cc \
	cc/tile.cc \
	cc/tile_draw_quad.cc \
	cc/tile_manager.cc \
	cc/tiled_layer.cc \
	cc/tiled_layer_impl.cc \
	cc/tiling_data.cc \
	cc/timing_function.cc \
	cc/transferable_resource.cc \
	cc/tree_synchronizer.cc \
	cc/video_layer.cc \
	cc/video_layer_impl.cc \
	cc/yuv_video_draw_quad.cc


# Flags passed to both C and C++ files.
MY_CFLAGS := \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	-Wno-error=extra \
	-Wno-error=ignored-qualifiers \
	-Wno-error=type-limits \
	-Wno-error=non-virtual-dtor \
	-Wno-error=sign-promo \
	-Wno-error=address \
	-Wno-error=format-security \
	-Wno-error=non-virtual-dtor \
	-Wno-error=return-type \
	-Wno-error=sequence-point \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

MY_CFLAGS_C :=

MY_DEFS := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DCC_IMPLEMENTATION=1' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_USE_POSIX_THREADS' \
	'-DSK_BUILD_FOR_ANDROID_NDK' \
	'-DPOSIX_AVOID_MMAP' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DUSE_SYSTEM_ICU' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_SYMBOLS_ID=""' \
	'-DANDROID_UPSTREAM_BRINGUP=1' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

LOCAL_CFLAGS := $(MY_CFLAGS_C) $(MY_CFLAGS) $(MY_DEFS)

# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/third_party/WebKit/Source/Platform/chromium \
	$(LOCAL_PATH)/third_party/khronos \
	$(LOCAL_PATH) \
	$(LOCAL_PATH)/skia/config \
	$(LOCAL_PATH)/third_party/skia/src/core \
	$(LOCAL_PATH)/third_party/skia/include/config \
	$(LOCAL_PATH)/third_party/skia/include/core \
	$(LOCAL_PATH)/third_party/skia/include/effects \
	$(LOCAL_PATH)/third_party/skia/include/pdf \
	$(LOCAL_PATH)/third_party/skia/include/gpu \
	$(LOCAL_PATH)/third_party/skia/include/gpu/gl \
	$(LOCAL_PATH)/third_party/skia/include/pipe \
	$(LOCAL_PATH)/third_party/skia/include/ports \
	$(LOCAL_PATH)/third_party/skia/include/utils \
	$(LOCAL_PATH)/skia/ext \
	$(LOCAL_PATH)/third_party/harfbuzz/contrib \
	$(LOCAL_PATH)/third_party/harfbuzz/src \
	$(LOCAL_PATH)/third_party/mesa/MesaLib/include \
	$(gyp_shared_intermediate_dir)/ui/gl \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/common \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/i18n \
	$(gyp_shared_intermediate_dir)/webcore_headers \
	$(LOCAL_PATH)/third_party/npapi \
	$(LOCAL_PATH)/third_party/npapi/bindings \
	$(LOCAL_PATH)/v8/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/frameworks/wilhelm/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/bionic \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/stlport/stlport

LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES)

# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated \
	-Wno-abi \
	-Wno-error=c++0x-compat

### Rules for final target.

LOCAL_LDFLAGS := \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	-Wl,--icf=safe \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections


LOCAL_STATIC_LIBRARIES := \
	skia_skia_gyp \
	ui_gl_gl_gyp

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES := \
	libstlport \
	libdl

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: cc_cc_gyp

# Alias gyp target name.
.PHONY: cc
cc: cc_cc_gyp

include $(BUILD_STATIC_LIBRARY)
