# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := ppapi_ppapi_proxy_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(call intermediates-dir-for,STATIC_LIBRARIES,skia_skia_gyp)/skia_skia_gyp.a \
	$(call intermediates-dir-for,GYP,ppapi_ppapi_c_gyp)/ppapi_c.stamp

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_CPP_EXTENSION := .cc
LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	ppapi/proxy/audio_input_resource.cc \
	ppapi/proxy/broker_dispatcher.cc \
	ppapi/proxy/dispatcher.cc \
	ppapi/proxy/file_chooser_resource.cc \
	ppapi/proxy/flash_device_id_resource.cc \
	ppapi/proxy/flash_font_file_resource.cc \
	ppapi/proxy/flash_clipboard_resource.cc \
	ppapi/proxy/flash_resource.cc \
	ppapi/proxy/gamepad_resource.cc \
	ppapi/proxy/host_dispatcher.cc \
	ppapi/proxy/host_var_serialization_rules.cc \
	ppapi/proxy/interface_list.cc \
	ppapi/proxy/interface_proxy.cc \
	ppapi/proxy/plugin_array_buffer_var.cc \
	ppapi/proxy/plugin_dispatcher.cc \
	ppapi/proxy/plugin_globals.cc \
	ppapi/proxy/plugin_message_filter.cc \
	ppapi/proxy/plugin_resource.cc \
	ppapi/proxy/plugin_resource_tracker.cc \
	ppapi/proxy/plugin_var_serialization_rules.cc \
	ppapi/proxy/plugin_var_tracker.cc \
	ppapi/proxy/ppapi_command_buffer_proxy.cc \
	ppapi/proxy/ppb_audio_proxy.cc \
	ppapi/proxy/ppb_broker_proxy.cc \
	ppapi/proxy/ppb_buffer_proxy.cc \
	ppapi/proxy/ppb_core_proxy.cc \
	ppapi/proxy/ppb_file_io_proxy.cc \
	ppapi/proxy/ppb_file_ref_proxy.cc \
	ppapi/proxy/ppb_file_system_proxy.cc \
	ppapi/proxy/ppb_flash_proxy.cc \
	ppapi/proxy/ppb_flash_menu_proxy.cc \
	ppapi/proxy/ppb_flash_message_loop_proxy.cc \
	ppapi/proxy/ppb_graphics_2d_proxy.cc \
	ppapi/proxy/ppb_graphics_3d_proxy.cc \
	ppapi/proxy/ppb_host_resolver_private_proxy.cc \
	ppapi/proxy/ppb_image_data_proxy.cc \
	ppapi/proxy/ppb_instance_proxy.cc \
	ppapi/proxy/ppb_message_loop_proxy.cc \
	ppapi/proxy/ppb_network_monitor_private_proxy.cc \
	ppapi/proxy/ppb_pdf_proxy.cc \
	ppapi/proxy/ppb_talk_private_proxy.cc \
	ppapi/proxy/ppb_tcp_server_socket_private_proxy.cc \
	ppapi/proxy/ppb_tcp_socket_private_proxy.cc \
	ppapi/proxy/ppb_testing_proxy.cc \
	ppapi/proxy/ppb_udp_socket_private_proxy.cc \
	ppapi/proxy/ppb_url_loader_proxy.cc \
	ppapi/proxy/ppb_url_response_info_proxy.cc \
	ppapi/proxy/ppb_var_deprecated_proxy.cc \
	ppapi/proxy/ppb_video_capture_proxy.cc \
	ppapi/proxy/ppb_video_decoder_proxy.cc \
	ppapi/proxy/ppb_x509_certificate_private_proxy.cc \
	ppapi/proxy/ppp_class_proxy.cc \
	ppapi/proxy/ppp_content_decryptor_private_proxy.cc \
	ppapi/proxy/ppp_graphics_3d_proxy.cc \
	ppapi/proxy/ppp_input_event_proxy.cc \
	ppapi/proxy/ppp_instance_private_proxy.cc \
	ppapi/proxy/ppp_instance_proxy.cc \
	ppapi/proxy/ppp_messaging_proxy.cc \
	ppapi/proxy/ppp_mouse_lock_proxy.cc \
	ppapi/proxy/ppp_printing_proxy.cc \
	ppapi/proxy/ppp_text_input_proxy.cc \
	ppapi/proxy/ppp_video_decoder_proxy.cc \
	ppapi/proxy/printing_resource.cc \
	ppapi/proxy/proxy_array_output.cc \
	ppapi/proxy/proxy_channel.cc \
	ppapi/proxy/proxy_module.cc \
	ppapi/proxy/proxy_object_var.cc \
	ppapi/proxy/resource_creation_proxy.cc \
	ppapi/proxy/url_request_info_resource.cc \
	ppapi/proxy/websocket_resource.cc


# Flags passed to both C and C++ files.
MY_CFLAGS := \
	-Werror \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	-Wno-error=extra \
	-Wno-error=ignored-qualifiers \
	-Wno-error=type-limits \
	-Wno-error=non-virtual-dtor \
	-Wno-error=sign-promo \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

MY_CFLAGS_C :=

MY_DEFS := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DSK_BUILD_NO_IMAGE_ENCODE' \
	'-DSK_DEFERRED_CANVAS_USES_GPIPE=1' \
	'-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' \
	'-DGR_AGGRESSIVE_SHADER_OPTS=1' \
	'-DSK_USE_POSIX_THREADS' \
	'-DSK_BUILD_FOR_ANDROID_NDK' \
	'-DU_USING_ICU_NAMESPACE=0' \
	'-DUSE_SYSTEM_ICU' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DPPAPI_PROXY_IMPLEMENTATION' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_SYMBOLS_ID=""' \
	'-DANDROID_UPSTREAM_BRINGUP=1' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

LOCAL_CFLAGS := $(MY_CFLAGS_C) $(MY_CFLAGS) $(MY_DEFS)

# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/third_party/khronos \
	$(LOCAL_PATH) \
	$(LOCAL_PATH)/skia/config \
	$(LOCAL_PATH)/third_party/skia/src/core \
	$(LOCAL_PATH)/third_party/skia/include/config \
	$(LOCAL_PATH)/third_party/skia/include/core \
	$(LOCAL_PATH)/third_party/skia/include/effects \
	$(LOCAL_PATH)/third_party/skia/include/pdf \
	$(LOCAL_PATH)/third_party/skia/include/gpu \
	$(LOCAL_PATH)/third_party/skia/include/gpu/gl \
	$(LOCAL_PATH)/third_party/skia/include/pipe \
	$(LOCAL_PATH)/third_party/skia/include/ports \
	$(LOCAL_PATH)/third_party/skia/include/utils \
	$(LOCAL_PATH)/skia/ext \
	$(LOCAL_PATH)/third_party/harfbuzz/contrib \
	$(LOCAL_PATH)/third_party/harfbuzz/src \
	$(LOCAL_PATH)/third_party/WebKit/Source/Platform/chromium \
	$(gyp_shared_intermediate_dir)/webcore_headers \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/common \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/icu4c/i18n \
	$(LOCAL_PATH)/third_party/npapi \
	$(LOCAL_PATH)/third_party/npapi/bindings \
	$(LOCAL_PATH)/v8/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/frameworks/wilhelm/include \
	$(GYP_ABS_ANDROID_TOP_DIR)/bionic \
	$(GYP_ABS_ANDROID_TOP_DIR)/external/stlport/stlport

LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES)

# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Wno-abi \
	-Wno-error=c++0x-compat

### Rules for final target.

LOCAL_LDFLAGS := \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	-Wl,--icf=safe \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections


LOCAL_STATIC_LIBRARIES := \
	skia_skia_gyp

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES := \
	libstlport \
	libdl

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: ppapi_ppapi_proxy_gyp

# Alias gyp target name.
.PHONY: ppapi_proxy
ppapi_proxy: ppapi_ppapi_proxy_gyp

include $(BUILD_STATIC_LIBRARY)
